version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run check
      - deploy:
          name: NPM Package Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn compile
              echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
              npm publish --access public
            else
              echo "will not deploy from branch \"$CIRCLE_BRANCH\""
            fi
